services:
  photon:
    image: 'ghcr.io/rtuszik/photon-docker:latest'
    container_name: "photon-docker"
    environment:
      - COUNTRY_CODE=de
      - UPDATE_STRATEGY=DISABLED
      - UPDATE_INTERVAL=720h
      - LOG_LEVEL=INFO
    volumes:
      - photon_data:/photon/photon_data
    restart: unless-stopped
    ports:
      - "2322:2322"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2322/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.http.services.hwkwogssgsowsogkow448oo0-photon.loadbalancer.server.port=2322"

volumes:
  photon_data:
