services:
  photon:
    image: 'ghcr.io/rtuszik/photon-docker:latest'
    container_name: "photon-docker"
    environment:
      - COUNTRY_CODE=de
      - UPDATE_STRATEGY=DISABLED
      - UPDATE_INTERVAL=720h
      - LOG_LEVEL=INFO
    volumes:
      - photon_data:/photon/photon_data
    restart: unless-stopped
    labels:  # <- Hier fehlte die richtige Einrückung!
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowheaders=*"
     #  - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=https://foo.bar.org,https://example.org"
      - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.testheader.headers.addvaryheader=true"


volumes:
  photon_data:
