services:
  photon:
    image: 'ghcr.io/rtuszik/photon-docker:latest'
    container_name: "photon-docker"
    environment:
      - COUNTRY_CODE=de
      - UPDATE_STRATEGY=DISABLED
      - UPDATE_INTERVAL=720h
      - LOG_LEVEL=INFO
    volumes:
      - photon_data:/photon/photon_data
    restart: unless-stopped
volumes:
  photon_data:
